
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      #DATABASE_HOST: db
      #POSTGRES_USER: open-flights
      POSTGRES_PASSWORD: password
  redis:
    image: redis
  web:
    build: .
    volumes:
      - .:/myapp
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
