default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  #password: <%= ENV['OPEN-FLIGHTS_DATABASE_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: open-flights_development


test:
  <<: *default
  database: open-flights_test


production:
  <<: *default
  database: open-flights_production
  username: open-flights
  password: <%= ENV['OPEN_FLIGHTS_DATABASE_PASSWORD'] %>
  
  
