default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  #username: open-flights
  #password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: open-flights_development


test:
  <<: *default
  database: open-flights_test


production:
  <<: *default
  database: open-flights_production
  username: open-flights
  password: mypass
  #password: password
  
  
