default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  #password: password
  pool: 5

development:
  <<: *default
  database: open-flights_development


test:
  <<: *default
  database: open-flights_test


production:
  <<: *default
  database: open-flights_production
  username: open-flights
  password: <%= ENV['OPEN-FLIGHTS_DATABASE_PASSWORD'] %>
